"""phase2b: discovery/scope fields, org profiles, and three-part PCI report structure

Revision ID: 1c524f57a183
Revises: 7b412818ad12
Create Date: 2026-08-20 08:49:02.284083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c524f57a183'
down_revision = '7b412818ad12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('org_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('contact_name', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role')
    )
    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discovered_via', sa.String(length=50), nullable=False,
                                       server_default='customer_provided'))
        batch_op.add_column(sa.Column('is_out_of_scope', sa.Boolean(), nullable=True,
                                       server_default=sa.false()))
        batch_op.add_column(sa.Column('segmentation_attestation', sa.Text(), nullable=True))

    # Separate batch block: dropping the server default has to happen
    # AFTER the columns above are actually added and existing rows
    # backfilled. On SQLite, batch_alter_table recreates the table once
    # per `with` block using the FINAL column state -- folding this into
    # the block above collapses to "add NOT NULL column with no default"
    # for the table-recreation copy step, which fails against any
    # pre-existing rows. Splitting into two blocks is what makes the
    # backfill actually happen before the default is removed, on both
    # SQLite and Postgres.
    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.alter_column('discovered_via', server_default=None)

    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scan_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('report_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('overall_result', sa.String(length=20), nullable=True))
        batch_op.create_foreign_key('fk_report_scan_id', 'scan', ['scan_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.drop_constraint('fk_report_scan_id', type_='foreignkey')
        batch_op.drop_column('overall_result')
        batch_op.drop_column('report_type')
        batch_op.drop_column('scan_id')

    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.drop_column('segmentation_attestation')
        batch_op.drop_column('is_out_of_scope')
        batch_op.drop_column('discovered_via')

    op.drop_table('org_profile')
    # ### end Alembic commands ###
