"""phase1: nvd-backed cvss scoring and cve_cache table

Revision ID: 4484679e7452
Revises: db7820f2ef19
Create Date: 2026-08-16 17:37:03.967236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4484679e7452'
down_revision = 'db7820f2ef19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cve_cache',
    sa.Column('cve_id', sa.String(length=30), nullable=False),
    sa.Column('cvss_score', sa.Float(), nullable=False),
    sa.Column('cvss_source', sa.String(length=50), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('cve_id')
    )
    with op.batch_alter_table('finding', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cvss_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('cvss_source', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('finding', schema=None) as batch_op:
        batch_op.drop_column('cvss_source')
        batch_op.drop_column('cvss_score')

    op.drop_table('cve_cache')
    # ### end Alembic commands ###
