"""phase6: inconclusive-scan tracking and multi-tenant hosting evidence

Revision ID: 83228d98c165
Revises: e01bddfeeb94
Create Date: 2026-08-25 03:40:22.341270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83228d98c165'
down_revision = 'e01bddfeeb94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_shared_hosting', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('hosting_provider_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('hosting_evidence_note', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('hosting_evidence_file_path', sa.String(length=255), nullable=True))

    with op.batch_alter_table('scan_job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_inconclusive', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scan_job', schema=None) as batch_op:
        batch_op.drop_column('is_inconclusive')

    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.drop_column('hosting_evidence_file_path')
        batch_op.drop_column('hosting_evidence_note')
        batch_op.drop_column('hosting_provider_name')
        batch_op.drop_column('is_shared_hosting')

    # ### end Alembic commands ###
