"""phase5: login lockout fields and security hardening (no schema changes for CSRF/testssl/nmap/payment-script)

Revision ID: e01bddfeeb94
Revises: 185d3fba017d
Create Date: 2026-08-24 09:03:09.160093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e01bddfeeb94'
down_revision = '185d3fba017d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('failed_login_attempts', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('locked_until', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###

    # Backfill existing accounts to 0 rather than leaving NULL --
    # models.py's register_failed_login() is defensive against NULL
    # either way, but a clean 0 is more honest than an unset value for a
    # counter field.
    bind = op.get_bind()
    meta = sa.MetaData()
    user_table = sa.Table('user', meta, autoload_with=bind)
    bind.execute(user_table.update().where(user_table.c.failed_login_attempts.is_(None)).values(failed_login_attempts=0))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('locked_until')
        batch_op.drop_column('failed_login_attempts')

    # ### end Alembic commands ###
