"""phase2a: report retention window and dispute/compensating-control workflow

Revision ID: 7b412818ad12
Revises: 4484679e7452
Create Date: 2026-08-18 08:05:41.420399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b412818ad12'
down_revision = '4484679e7452'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dispute',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('finding_id', sa.Integer(), nullable=False),
    sa.Column('dispute_type', sa.String(length=50), nullable=False),
    sa.Column('submitted_by', sa.String(length=255), nullable=True),
    sa.Column('evidence_text', sa.Text(), nullable=True),
    sa.Column('evidence_file_path', sa.String(length=255), nullable=True),
    sa.Column('reviewed_by', sa.String(length=255), nullable=True),
    sa.Column('decision', sa.String(length=50), nullable=True),
    sa.Column('decision_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['finding_id'], ['finding.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expires_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('retention_until', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.drop_column('retention_until')
        batch_op.drop_column('expires_at')

    op.drop_table('dispute')
    # ### end Alembic commands ###
